[wokwi]
version = 1
firmware = "C:/Users/ALMASDAR/AppData/Local/Programs/Microsoft VS Code/.arduino/output/aa.ino.hex"
elf = "C:/Users/ALMASDAR/AppData/Local/Programs/Microsoft VS Code/.arduino/output/aa.ino.elf"
